from keysight.ads import de
from keysight.ads.de import db_uu as db
from keysight.ads.de.db import LayerId
from keysight.edatoolbox import ads
import os
import keysight.ads.dataset as dataset
import matplotlib.pyplot as plt
from IPython.core import getipython
from pathlib import Path
import numpy as np
import seaborn as sns

# --- Workspace Setup ---
# Get the current working directory as the workspace path
workspace_path = Path.cwd()
#print(script_path)

# --- Design Configuration ---
# Define the Library name and the Schematic (Cell) name
print("Please enter lib_name:/n")
print("Please enter schematic_name:/n")
lib_name = "SOA_Tran_Check.lib"
schematic_name = "TB_EF_Tran"

# --- Open Design ---
# Open the design using the standard ADS format: "Library:Cell:View"
design = db.open_design(f"{lib_name}:{schematic_name}:schematic")

# # insert simulation setup (Optional/Commented out)
# # The following lines would add a Transient Simulation controller to the schematic
# #option_inst = design.add_instance("Simulation-Transient:Options:symbol",(8,0))
# #design.save_design()
print("Please insert Options into schematic./n")
print("Please ensure output filters are all selected./n")
print("Please save branch currents./n")
print("Please save internal node voltages./n")

# --- Netlist Generation ---
# Generate the netlist from the open design object
netlist = design.generate_netlist()
#print(netlist)

# --- Simulation Execution ---
# Define the directory where simulation results will be stored (in the 'data' folder)
target_output_dir = os.path.join(workspace_path, "data")

# Initialize the Circuit Simulator object
simulator = ads.CircuitSimulator()

# Run the netlist simulation and direct output to the target directory
simulator.run_netlist(netlist, output_dir=target_output_dir)
print("Run successfully.")

# --- Data Processing ---
# Open the resulting dataset file (.ds) generated by the simulation
output_data = dataset.open(Path(os.path.join(target_output_dir, f"{schematic_name}" + ".ds")))
#print(output_data.varblock_names)

# --- Find Data Block ---
# Search for the variable block that contains the "time" variable (indicating transient results)
for data_block in output_data.find_varblocks_with_var_name("time"):
    print("time is found in:", data_block.name)
    time_block_name = data_block.name

# --- Convert to DataFrame ---
# 1. Select the correct data block.
# 2. Convert it to a Pandas DataFrame.
# 3. Use reset_index() to move the index (likely 'time') into a standard column.
mydata = output_data[time_block_name].to_dataframe().reset_index()

# --- Export to CSV ---
# Define the file path for the CSV output
csv_file_path = os.path.join(target_output_dir, f"{schematic_name}" + ".csv")

# Write the DataFrame to a CSV file
mydata.to_csv(csv_file_path)

print("Ds is converted to Dataframe.")